import fs from 'fs'
import path from 'path'
import OpenAI from 'openai'
import { randomUUID } from 'crypto'
import { createDraftLayout } from '@/lib/layout/mapper'
import {
  createSection,
  type Field,
  type PageLayout,
  type Section,
  type ThemeTokens,
} from '@/lib/layout/schema'
import { sanitizeAndEnhanceHtml, TEMPLATE_THEMES } from './websiteHtmlSanitizer'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export interface WebsiteGeneratorInput {
  dashboardId: string
  businessName: string
  niche: string
  productService: string
  targetAudience: string
  pricingModel: string
  primaryGoal: string
  biggestChallenge: string
  brandTone?: string
  businessCaseContent?: string
  templateId: number
}

export interface WebsiteGenerationResult {
  layout: PageLayout
  previewHtml: string
  metadata: {
    templateId: number
    templateName: string
    sections: string[]
    colorScheme: string
    themeMode: 'light' | 'dark'
  }
}

export async function generateWebsite(input: WebsiteGeneratorInput): Promise<WebsiteGenerationResult> {
  try {
    // Check for OpenAI API key
    if (!process.env.OPENAI_API_KEY) {
      throw new Error('OPENAI_API_KEY environment variable is not set')
    }

    // Load system prompt
    const promptPath = path.join(process.cwd(), 'lib/ai/prompts/website_templates.txt')
    
    if (!fs.existsSync(promptPath)) {
      throw new Error(`Template prompt file not found at: ${promptPath}`)
    }
    
    const systemPrompt = fs.readFileSync(promptPath, 'utf-8')

    // Determine template structure based on templateId
    const templateConfig = getTemplateConfig(input.templateId)
    const themeConfig = TEMPLATE_THEMES[input.templateId as keyof typeof TEMPLATE_THEMES]
    
    // Create enhanced user prompt with business data
    const userPrompt = `
Business Name: ${input.businessName}
Niche/Industry: ${input.niche}
Product/Service Offering: ${input.productService}
Target Audience: ${input.targetAudience}
Pricing Model: ${input.pricingModel}
Primary Goal: ${input.primaryGoal}
Biggest Challenge: ${input.biggestChallenge}
Brand Tone: ${input.brandTone || 'professional and engaging'}

Template: ${templateConfig.name} (ID: ${templateConfig.id})
Template Description: ${templateConfig.description}
Theme Mode: ${themeConfig?.mode || 'light'} mode preferred

${input.businessCaseContent ? `\nBusiness Context from Business Case:\n${input.businessCaseContent.substring(0, 1000)}\n` : ''}

CRITICAL REQUIREMENTS:
1. Generate a complete, production-ready website following the ${templateConfig.name} template structure
2. ALL sections MUST have proper IDs: hero, about, features, cta, footer
3. Use section-specific background colors - DO NOT set text-white on <body> or <html> tags
4. Ensure proper contrast: light sections use dark text (text-gray-900), dark sections use light text (text-white)
5. Include at least ONE clear call-to-action button in the hero section
6. Use semantic HTML5 elements: <header>, <main>, <section>, <footer>
7. Make it fully responsive with mobile-first Tailwind classes
8. Include descriptive alt text on ALL images
9. Use high-quality Unsplash images relevant to ${input.niche}

Return ONLY valid HTML without any markdown formatting, code blocks, or explanations.
The HTML should be self-contained and ready to render.
    `.trim()

    console.log(`[Website Generator] Calling OpenAI API for template ${input.templateId}...`)

    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.7,
      max_tokens: 8000,
    })

    console.log(`[Website Generator] OpenAI API call successful`)

    const generatedHtml = completion.choices[0]?.message?.content || ''
    
    if (!generatedHtml) {
      throw new Error('OpenAI returned empty response')
    }
    
    // Use enhanced sanitization pipeline
    const sanitized = sanitizeAndEnhanceHtml(
      generatedHtml,
      input.templateId,
      input.businessName
    )

    const themeTokens = resolveThemeTokens(input.templateId)
    const sections = buildSectionsFromHtml(sanitized.html)

    const layout = createDraftLayout({
      dashboardId: input.dashboardId,
      slug: slugify(input.businessName),
      theme: themeTokens,
      sections,
      metadata: {
        title: `${input.businessName} — ${templateConfig.name}`,
        description: `${input.businessName} website generated by Project 67`,
        templateId: input.templateId,
        templateName: templateConfig.name,
        seoKeywords: [input.niche, input.productService, input.primaryGoal].filter(Boolean),
      },
    })

    return {
      layout,
      previewHtml: sanitized.html,
      metadata: {
        templateId: input.templateId,
        templateName: templateConfig.name,
        sections: layout.sections.map((section) => section.type),
        colorScheme: sanitized.metadata.colorScheme,
        themeMode: themeConfig?.mode || 'light',
      },
    }
  } catch (error) {
    console.error('Error generating website:', error)
    // Provide more specific error details
    if (error instanceof Error) {
      throw new Error(`Failed to generate website: ${error.message}`)
    }
    throw new Error('Failed to generate website: Unknown error')
  }
}

function getTemplateConfig(templateId: number) {
  const templates = [
    { id: 1, name: 'Luxury Minimalist', description: 'Clean, elegant design for premium brands with plenty of white space' },
    { id: 2, name: 'Bold & Modern', description: 'High-impact visuals for tech startups with bold typography and vibrant colors' },
    { id: 3, name: 'Playful Creative', description: 'Fun, vibrant layouts for creative businesses with playful elements' },
    { id: 4, name: 'Professional Corporate', description: 'Traditional, trustworthy design for established businesses' },
    { id: 5, name: 'Wellness & Lifestyle', description: 'Calm, inviting design for health brands with soft colors' },
    { id: 6, name: 'E-commerce Pro', description: 'Conversion-optimized for online stores with product showcases' },
    { id: 7, name: 'Agency Portfolio', description: 'Showcase your work with style and modern grid layouts' },
    { id: 8, name: 'SaaS Landing', description: 'Convert visitors to customers with clear value propositions and CTAs' },
  ]
  
  return templates.find(t => t.id === templateId) || templates[0]
}

function resolveThemeTokens(templateId: number): ThemeTokens {
  const presets: Record<number, ThemeTokens> = {
    1: {
      palette: {
        primary: '#111827',
        secondary: '#1f2937',
        accent: '#b45309',
        background: '#ffffff',
        surface: '#f9fafb',
        muted: '#e5e7eb',
        textPrimary: '#111827',
        textSecondary: '#4b5563',
      },
      typography: {
        heading: 'Playfair Display',
        body: 'Inter',
        accent: 'Inter',
        scale: 'md',
      },
      spacing: {
        base: 4,
        radius: 16,
        gap: 6,
      },
    },
    2: {
      palette: {
        primary: '#1e3a8a',
        secondary: '#7c3aed',
        accent: '#f59e0b',
        background: '#0f172a',
        surface: '#1e293b',
        muted: '#334155',
        textPrimary: '#f8fafc',
        textSecondary: '#cbd5f5',
      },
      typography: {
        heading: 'Inter',
        body: 'Inter',
        accent: 'Space Grotesk',
        scale: 'md',
      },
      spacing: {
        base: 5,
        radius: 20,
        gap: 6,
      },
    },
    3: {
      palette: {
        primary: '#db2777',
        secondary: '#f97316',
        accent: '#14b8a6',
        background: '#fff7ed',
        surface: '#fffbeb',
        muted: '#fed7aa',
        textPrimary: '#1f2937',
        textSecondary: '#4b5563',
      },
      typography: {
        heading: 'Playfair Display',
        body: 'Inter',
        accent: 'DM Sans',
        scale: 'md',
      },
      spacing: {
        base: 4,
        radius: 18,
        gap: 5,
      },
    },
    4: {
      palette: {
        primary: '#1d4ed8',
        secondary: '#0f172a',
        accent: '#0369a1',
        background: '#f8fafc',
        surface: '#ffffff',
        muted: '#e2e8f0',
        textPrimary: '#1f2937',
        textSecondary: '#475569',
      },
      typography: {
        heading: 'Inter',
        body: 'Inter',
        accent: 'Roboto',
        scale: 'md',
      },
      spacing: {
        base: 4,
        radius: 16,
        gap: 6,
      },
    },
    5: {
      palette: {
        primary: '#047857',
        secondary: '#0f766e',
        accent: '#f59e0b',
        background: '#f9fafb',
        surface: '#ffffff',
        muted: '#d1fae5',
        textPrimary: '#14532d',
        textSecondary: '#166534',
      },
      typography: {
        heading: 'Playfair Display',
        body: 'Inter',
        accent: 'Lora',
        scale: 'sm',
      },
      spacing: {
        base: 4,
        radius: 20,
        gap: 5,
      },
    },
    6: {
      palette: {
        primary: '#0ea5e9',
        secondary: '#2563eb',
        accent: '#f97316',
        background: '#f8fafc',
        surface: '#ffffff',
        muted: '#e0f2fe',
        textPrimary: '#0f172a',
        textSecondary: '#1e293b',
      },
      typography: {
        heading: 'Inter',
        body: 'Inter',
        accent: 'Space Grotesk',
        scale: 'md',
      },
      spacing: {
        base: 4,
        radius: 18,
        gap: 5,
      },
    },
    7: {
      palette: {
        primary: '#0ea5e9',
        secondary: '#7c3aed',
        accent: '#f472b6',
        background: '#020617',
        surface: '#111827',
        muted: '#1f2937',
        textPrimary: '#e2e8f0',
        textSecondary: '#94a3b8',
      },
      typography: {
        heading: 'Space Grotesk',
        body: 'Inter',
        accent: 'Inter',
        scale: 'lg',
      },
      spacing: {
        base: 5,
        radius: 24,
        gap: 6,
      },
    },
    8: {
      palette: {
        primary: '#2563eb',
        secondary: '#7c3aed',
        accent: '#22d3ee',
        background: '#ffffff',
        surface: '#f8fafc',
        muted: '#e0f2fe',
        textPrimary: '#0f172a',
        textSecondary: '#475569',
      },
      typography: {
        heading: 'Inter',
        body: 'Inter',
        accent: 'Space Grotesk',
        scale: 'md',
      },
      spacing: {
        base: 4,
        radius: 18,
        gap: 6,
      },
    },
  }

  return presets[templateId] ?? presets[1]
}

function buildSectionsFromHtml(html: string): Section[] {
  const sectionRegex = /<section([^>]*)>([\s\S]*?)<\/section>/gi
  const sections: Section[] = []
  let match: RegExpExecArray | null
  let index = 0

  while ((match = sectionRegex.exec(html))) {
    const attributes = match[1] || ''
    const innerHtml = match[2] || ''
    const sectionId = extractAttribute(attributes, 'id') || `section-${index + 1}`
    const label = humanizeLabel(sectionId)
    const variant = deriveVariant(sectionId, attributes, innerHtml)
    const fields: Field[] = []

    const heading = extractFirst(innerHtml, /<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i)
    if (heading) {
      fields.push({
        kind: 'text',
        key: 'heading',
        label: 'Heading',
        value: stripHtml(heading),
        multiline: false,
      })
    }

    const subheading = extractFirst(innerHtml, /<p[^>]*class="[^"]*text-(lg|xl)[^"]*"[^>]*>([\s\S]*?)<\/p>/i)
    const firstParagraph = subheading || extractFirst(innerHtml, /<p[^>]*>([\s\S]*?)<\/p>/i)
    if (firstParagraph) {
      fields.push({
        kind: 'richText',
        key: 'body',
        label: 'Body',
        markdown: stripHtml(firstParagraph).trim(),
      })
    }

    const imageMatch = /<img[^>]*src="([^"]+)"[^>]*alt="([^"]*)"[^>]*>/i.exec(innerHtml)
    if (imageMatch) {
      fields.push({
        kind: 'image',
        key: 'image',
        label: 'Primary Image',
        url: imageMatch[1],
        alt: imageMatch[2] || label,
      })
    }

    const ctaMatch = /<a[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i.exec(innerHtml)
    if (ctaMatch) {
      fields.push({
        kind: 'link',
        key: 'primaryCta',
        label: 'Primary CTA',
        href: ctaMatch[1],
        text: stripHtml(ctaMatch[2]),
        style: 'primary',
      })
    }

    // Preserve raw HTML for advanced editing
    fields.push({
      kind: 'richText',
      key: 'rawHtml',
      label: 'Raw HTML',
      markdown: innerHtml.trim(),
    })

    sections.push(
      createSection({
        id: sectionId,
        label,
        variant,
        fields,
      })
    )

    index += 1
  }

  if (sections.length === 0) {
    sections.push(
      createSection({
        id: randomUUID(),
        label: 'Hero',
        variant: 'hero',
        fields: [
          { kind: 'text', key: 'heading', label: 'Heading', value: 'Welcome to your new website', multiline: false },
          {
            kind: 'richText',
            key: 'body',
            label: 'Body',
            markdown: 'Add your content here.',
          },
        ],
      })
    )
  }

  return sections
}

function extractAttribute(attributes: string, attribute: string) {
  const regex = new RegExp(`${attribute}\\s*=\\s*"(.*?)"`, 'i')
  const match = attributes.match(regex)
  if (match) return match[1]

  const singleQuoteRegex = new RegExp(`${attribute}\\s*=\\s*'(.*?)'`, 'i')
  const singleQuoteMatch = attributes.match(singleQuoteRegex)
  return singleQuoteMatch ? singleQuoteMatch[1] : null
}

function extractFirst(content: string, regex: RegExp) {
  const match = regex.exec(content)
  return match ? match[1] : null
}

function stripHtml(value: string) {
  return value.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim()
}

function humanizeLabel(value: string) {
  return value
    .replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase())
}

function deriveVariant(id: string, attributes: string, content: string): string {
  const combined = `${id} ${attributes} ${content}`.toLowerCase()

  if (combined.includes('hero') || combined.includes('banner')) return 'hero'
  if (combined.includes('feature') || combined.includes('value')) return 'feature-grid'
  if (combined.includes('testimonial') || combined.includes('review')) return 'testimonial'
  if (combined.includes('pricing')) return 'pricing'
  if (combined.includes('faq')) return 'faq'
  if (combined.includes('cta') || combined.includes('call-to-action')) return 'cta'
  if (combined.includes('footer')) return 'footer'

  return 'custom'
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || `layout-${Date.now()}`
}


